# Ex - GroupBy

### Introduction:

GroupBy can be summarized as Split-Apply-Combine.

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

Check out this [Diagram](http://i.imgur.com/yjNkiwL.png)  
### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://github.com/thieu1995/csv-files/blob/main/data/pandas/drinks.csv).

### Step 3. Assign it to a variable called drinks.

In [5]:
drinks = pd.read_csv('https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/drinks.csv')
drinks

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF
...,...,...,...,...,...,...
188,Venezuela,333,100,3,7.7,SA
189,Vietnam,111,2,1,2.0,AS
190,Yemen,6,0,0,0.1,AS
191,Zambia,32,19,4,2.5,AF
192,Zimbabwe,64,18,4,4.7,AF

###Step 4. Which continent drinks more beer on average?

In [7]:
drinks.groupby('continent').beer_servings.mean().sort_values(ascending=False)

continent
EU    193.777778
SA    175.083333
OC     89.687500
AF     61.471698
AS     37.045455
Name: beer_servings, dtype: float64

### Step 5. For each continent print the statistics for wine consumption.

In [8]:
drinks.groupby('continent').wine_servings.mean()

continent
AF     16.264151
AS      9.068182
EU    142.222222
OC     35.625000
SA     62.416667
Name: wine_servings, dtype: float64

### Step 6. Print the mean alcohol consumption per continent for every column

In [10]:
drinks.groupby('continent').total_litres_of_pure_alcohol.mean()

continent
AF    3.007547
AS    2.170455
EU    8.617778
OC    3.381250
SA    6.308333
Name: total_litres_of_pure_alcohol, dtype: float64

### Step 7. Print the median alcohol consumption per continent for every column

In [11]:
drinks.total_litres_of_pure_alcohol.median()

4.2

### Step 8. Print the mean, min and max values for spirit consumption.
#### This time output a DataFrame

In [12]:
print(f"The mean for spririt consumption is {drinks.spirit_servings.mean()}")
print(f"The min for spririt consumption is {drinks.spirit_servings.min()}")
print(f"The max for spririt consumption is {drinks.spirit_servings.max()}")

The mean for spririt consumption is 80.99481865284974
The min for spririt consumption is 0
The max for spririt consumption is 438